StarCraft/StarCraft.Web/Areas/Admin/Controllers/UnitsController.cs
namespace StarCraft.Web.Areas.Admin.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using StarCraft.Data;
    using StarCraft.Services.Admin.Contracts;
    using StarCraft.Services.Models;
    using StarCraft.Web.Areas.Admin.Models.Units;
    using StarCraft.Web.Controllers;
    using StarCraft.Web.Infrastructure.Extensions;
    using static WebConstants;

    public class UnitsController : AdminBaseController
    {
        private readonly IAdminUnitsService units;

        public UnitsController(IAdminUnitsService units)
        {
            this.units = units;
        }

        public async Task<IActionResult> AllUnits()
        {
            var result = await this.units.AllUnitsAsync();

            return this.View(result);
        }

        public async Task<IActionResult> CreateUnit()
        {
            var buildings = await this.units.GetAllBuildingsFormAsync();

            return this.View(new CreateUnitModel
            {
                Buildings = buildings
            });
        }

        [HttpPost]
        public async Task<IActionResult> CreateUnit(CreateUnitModel unitModel, IFormFile image)
        {
            bool exists = await this.units.DoesUnitExistsAsync(unitModel.Name);

            if (exists)
            {
                ModelState.AddModelError(string.Empty, $"The unit {unitModel.Name} exists.");
            }

            if (!ModelState.IsValid)
            {
                unitModel.Buildings = await this.units.GetAllBuildingsFormAsync();
                return this.View(unitModel);
            }

            byte[] fileContents = await image.ToByteArrayAsync();

            if (!image.FileName.EndsWith(ImageFormat) || image.Length > DataConstants.MaxByteImageSize)
            {
                TempData.AddErrorMessage("The image was no in the correct format or the size was more that 5mb");
                return this.RedirectToAction(nameof(this.CreateUnit));
            }

            await this.units.CreateUnitAsync(
                unitModel.Name,
                unitModel.UnlockLevel,
                unitModel.ExpWorth,
                unitModel.MineralCost,
                unitModel.GasCost,
                unitModel.Health,
                unitModel.Damage,
                unitModel.Building,
                fileContents);

            TempData.AddSuccessMessage($"Unit {unitModel.Name} created successfully!");

            return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var unit = await this.units.FindByIdAsync(id);

            if (unit == null)
            {
                ModelState.AddModelError(string.Empty, UnitNotFoundMessage);
                return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
            }

            return this.View(new UnitServiceModel
            {
                Name = unit.Name,
                ExpWorth = unit.ExpWorth,
                UnlockLevel = unit.UnlockLevel,
                MineralCost = unit.MineralCost,
                GasCost = unit.GasCost,
                Health = unit.Health,
                Damage = unit.Damage,
                Image = unit.Image
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, UnitServiceModel model, IFormFile image)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var unit = await this.units.FindByIdAsync(id);

            if (unit == null)
            {
                ModelState.AddModelError(string.Empty, UnitNotFoundMessage);
                return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
            }

            var found = await this.units.DoesUnitExistsAsync(model.Name);

            if (found)
            {
                TempData.AddErrorMessage(UnitExistsMessage);
                return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
            }

            byte[] fileContents = await image.ToByteArrayAsync();

            if (!image.FileName.EndsWith(ImageFormat) || image.Length > DataConstants.MaxByteImageSize)
            {
                return this.View(nameof(this.CreateUnit));
            }

            await this.units.EditAsync(id, model.Name, model.ExpWorth, model.UnlockLevel, model.MineralCost, model.GasCost, model.Health, model.Damage, fileContents);

            return this.RedirectToAction(nameof(this.AllUnits));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var unit = await this.units.FindByIdAsync(id);

            if (unit == null)
            {
                ModelState.AddModelError(string.Empty, UnitNotFoundMessage);
                return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
            }

            return this.View(new DeleteUnitModel
            {
                Id = id,
                Unit = new UnitServiceModel
                {
                    Name = unit.Name,
                    UnlockLevel = unit.UnlockLevel,
                    ExpWorth = unit.ExpWorth,
                    MineralCost = unit.MineralCost,
                    GasCost = unit.GasCost,
                    Health = unit.Health,
                    Damage = unit.Damage,
                    Image = unit.Image
                }
            });
        }

        public async Task<IActionResult> DeleteUnit(int id)
        {
            var building = await this.units.FindByIdAsync(id);

            if (building == null)
            {
                ModelState.AddModelError(string.Empty, UnitNotFoundMessage);
                return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
            }

            await this.units.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.AllUnits));
        }
    }
}

StarCraft/StarCraft.Web/Controllers/UsersController.cs
namespace StarCraft.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using StarCraft.Data.Models;
    using StarCraft.Services;
    using StarCraft.Services.Contracts;
    using StarCraft.Services.Models;
    using StarCraft.Web.Infrastructure.Extensions;
    using StarCraft.Web.Models.Buildings;
    using StarCraft.Web.Models.UsersViewModels;
    using static WebConstants;

    [Authorize]
    public class UsersController : Controller
    {
        private readonly IUserService users;
        private readonly IBuildingService buildings;
        private readonly IUnitService units;
        private readonly UserManager<User> userManager;

        public UsersController(IUserService users, IBuildingService buildings, IUnitService units, UserManager<User> userManager)
        {
            this.users = users;
            this.buildings = buildings;
            this.units = units;
            this.userManager = userManager;
        }

        public async Task<IActionResult> BuyBuilding()
        {
            User user = await this.userManager.FindByNameAsync(User.Identity.Name);

            var buildings = await this.buildings.AllBuildingsAsync(user.Id, user.Level, user.Race);

            string currentExp = GetUserExp(user);

            return this.View(new UserBuyBuildingsViewModel
            {
                Buildings = buildings,
                Level = user.Level,
                CurrentExp = currentExp,
                Minerals = user.Minerals,
                Gas = user.Gas
            });
        }

        [HttpPost]
        public async Task<IActionResult> BuyBuilding(int buildingId)
        {
            string userId = this.userManager.GetUserId(User);

            Tuple<bool, string> success = await this.users.BuyBuildingAsync(buildingId, userId);

            if (!success.Item1)
            {
                TempData.AddErrorMessage(success.Item2);
                return this.RedirectToAction(nameof(UsersController.BuyBuilding));
            }

            TempData.AddSuccessMessage(success.Item2);

            return this.RedirectToAction(nameof(this.BuyBuilding));
        }

        public async Task<IActionResult> BuyUnit()
        {
            User user = await this.userManager.FindByNameAsync(User.Identity.Name);

            var units = await this.units.AllUnitsAsync(user.Id, user.Race);
            var userUnits = await this.users.GetUserUnitsAsync(user.Id);

            string currentExp = GetUserExp(user);

            return this.View(new UserBuyUnitsViewModel
            {
                Units = units,
                Level = user.Level,
                CurrentExp = currentExp,
                Minerals = user.Minerals,
                Gas = user.Gas,
                BoughtUnits = userUnits
            });
        }

        [HttpPost]
        public async Task<IActionResult> BuyUnit(int unitId, int quantity)
        {
            string userId = this.userManager.GetUserId(User);

            Tuple<bool, string> success = await this.users.BuyUnitAsync(unitId, userId, quantity);

            if (!success.Item1)
            {
                TempData.AddErrorMessage(success.Item2);
                return this.RedirectToAction(nameof(UsersController.BuyUnit));
            }

            TempData.AddSuccessMessage(success.Item2);

            return this.RedirectToAction(nameof(this.BuyUnit));
        }

        public async Task<IActionResult> FindRandomPlayer()
        {
            string userId = this.userManager.GetUserId(User);

            var enemy = await this.users.FindRandomPlayerAsync(userId);
            var user = await this.users.UserBattleInfoAsync(userId);

            if (enemy == null || user == null)
            {
                TempData.AddErrorMessage("No enemies found or you don't have enough troops.");

                return this.RedirectToAction(nameof(HomeController.Index), HomeControllerName, new { area = string.Empty });
            }

            return this.View(new BattleServiceModel
            {
                User = user,
                Enemy = enemy
            });
        }

        public async Task<IActionResult> BattleEnemy(string enemyId)
        {
            string userId = this.userManager.GetUserId(User);

            var result = await this.users.BattleEnemyAsync(userId, enemyId);

            if (result == null)
            {
                TempData.AddErrorMessage("No enemies found or you don't have enough troops.");
                return this.RedirectToAction(nameof(this.FindRandomPlayer));
            }

            return this.View(result);
        }

        private static string GetUserExp(User user)
        {
            string currentExp = "Max level";
            if (typeof(ServiceConstants).GetField("ExpForLevel" + user.Level) != null)
            {
                currentExp = $"{user.CurrentExp}/{(int)typeof(ServiceConstants).GetField("ExpForLevel" + user.Level).GetValue(null)}";
            }

            return currentExp;
        }
    }
}

StarCraft/StarCraft.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - StarCraft</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">StarCraft</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(WebConstants.AdministratorRole))
                    {
                        <li><a asp-area="Admin" asp-controller="Buildings" asp-action="AllBuildings">All buildings</a></li>
                        <li><a asp-area="Admin" asp-controller="Units" asp-action="AllUnits">All units</a></li>
                        <li><a asp-area="Admin" asp-controller="Buildings" asp-action="CreateBuilding">Add new buildings</a></li>
                        <li><a asp-area="Admin" asp-controller="Units" asp-action="CreateUnit">Add new unit</a></li>
                        <li><a asp-area="Admin" asp-controller="Users" asp-action="AllUsers">All users</a></li>
                    }
                    else if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="BuyBuilding">Buy new building</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="BuyUnit">Buy new unit</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="FindRandomPlayer">Find a player to battle</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempDataSuccessMessageKey]
            </div>
        }

        @if (TempData.ContainsKey(WebConstants.TempDataErrorMessageKey))
        {
            <div class="alert alert-danger">
                @TempData[WebConstants.TempDataErrorMessageKey]
            </div>
        }

        @RenderBody()
        <hr />
        <footer class="text-right">
            <p>&copy; 2017 - StarCraft</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>